#---
#kind: ClusterRole
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: pods
#rules:
#  - apiGroups: ["*"]
#    resources: ["pods"]
#    verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
#---
#kind: ClusterRoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: pods
#subjects:
#  - kind: ServiceAccount
#    name: default
#    namespace: default
#roleRef:
#  kind: ClusterRole
#  name: pods
#  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dltk-dask-runtime-client
spec:
  selector:
    matchLabels:
      app: dltk-dask-runtime
      component: client
  replicas: 1
  template:
    metadata:
      labels:
        app: dltk-dask-runtime
        component: client
    spec:
      containers:
        - name: runtime
          image: runtime:latest
          imagePullPolicy: Never
#          resources:
#            limits:
#              cpu: "100m"
#              memory: 100M
#            requests:
#              cpu: "100m"
#              memory: 100M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dltk-dask-runtime-scheduler
spec:
  selector:
    matchLabels:
      app: dltk-dask-runtime
      component: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: dltk-dask-runtime
        component: scheduler
    spec:
      containers:
        - name: scheduler
          image: daskdev/dask
          command:
            - dask-scheduler
          imagePullPolicy: Never
#          resources:
#            limits:
#              cpu: "100m"
#              memory: 100M
#            requests:
#              cpu: "100m"
#              memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: dltk-dask-runtime-scheduler
spec:
  type: NodePort
  selector:
    app: dltk-dask-runtime
    component: scheduler
  ports:
    - name: dashboard
      protocol: TCP
      port: 8787
      targetPort: 8787
    - name: scheduler
      protocol: TCP
      port: 8786
      targetPort: 8786
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dltk-dask-runtime-worker
spec:
  selector:
    matchLabels:
      app: dltk-dask-runtime
      component: worker
  replicas: 2
  template:
    metadata:
      labels:
        app: dltk-dask-runtime
        component: worker
    spec:
      containers:
        - name: worker
          image: daskdev/dask
          imagePullPolicy: Never
          command:
            - dask-worker
            - dltk-dask-runtime-scheduler:8786
#          --nthreads,
#          "1",
#          --no-bokeh,
#          --memory-limit,
#          1GB,
#          --death-timeout,
#          "60",
#          resources:
#            limits:
#              cpu: "1"
#              memory: 1Gi
#            requests:
#              cpu: "1"
#              memory: 1Gi
